import type {
  ActivityEvent,
  Branch,
  Comment,
  Project,
  TeamMemory,
  Timeline,
} from "./types";

export const PROJECT_ID = "project-yc-launch";

export const seedProject: Project = {
  id: PROJECT_ID,
  name: "YC Startup Launch Video",
  description: "A 60-second product launch video for a voice AI startup.",
  videoUrl: undefined,
  createdAt: "2026-06-20T09:00:00.000Z",
};

const mainCutTimeline: Timeline = {
  duration: 60,
  globalStyle: {
    pacing: "medium",
    colorGrade: "neutral",
    musicMood: "calm",
    captionStyle: "minimal_white",
    brandTone: "clear_b2b",
  },
  clips: [
    {
      id: "clip_hook",
      name: "Hook",
      type: "video",
      start: 0,
      end: 8,
      order: 1,
      caption: "AI agents that talk like your best teammate",
      transition: "fade",
      notes: "Opening hook",
    },
    {
      id: "clip_problem",
      name: "Problem",
      type: "video",
      start: 8,
      end: 20,
      order: 2,
      caption: "Support teams are drowning in repetitive calls",
      transition: "cut",
      notes: "Pain point",
    },
    {
      id: "clip_product",
      name: "Product Demo",
      type: "video",
      start: 20,
      end: 38,
      order: 3,
      caption: "Deploy voice agents in minutes",
      transition: "slide",
      notes: "Product explanation",
    },
    {
      id: "clip_testimonial",
      name: "Customer Proof",
      type: "video",
      start: 38,
      end: 50,
      order: 4,
      caption: "Reduced support load by 40%",
      transition: "cut",
      notes: "Trust builder",
    },
    {
      id: "clip_cta",
      name: "CTA",
      type: "video",
      start: 50,
      end: 60,
      order: 5,
      caption: "Book a demo today",
      transition: "fade_out",
      notes: "Call to action",
    },
  ],
  audio: {
    musicMood: "calm",
    volume: 70,
    voiceoverVolume: 90,
  },
  captions: {
    style: "minimal_white",
    font: "Inter",
    size: "medium",
    position: "bottom_center",
  },
};

const fastReelCutTimeline: Timeline = {
  duration: 35,
  globalStyle: {
    pacing: "fast",
    colorGrade: "warm",
    musicMood: "energetic",
    captionStyle: "bold_yellow",
    brandTone: "playful_direct",
  },
  clips: [
    {
      id: "clip_hook",
      name: "Hook",
      type: "video",
      start: 0,
      end: 3,
      order: 1,
      caption: "Meet the AI teammate for support teams",
      transition: "cut",
      notes: "Faster hook for social feeds",
    },
    {
      id: "clip_problem",
      name: "Problem",
      type: "video",
      start: 3,
      end: 10,
      order: 2,
      caption: "Support teams are drowning in repetitive calls",
      transition: "cut",
      notes: "Pain point, trimmed",
    },
    {
      id: "clip_testimonial",
      name: "Customer Proof",
      type: "video",
      start: 10,
      end: 18,
      order: 3,
      caption: "Reduced support load by 40%",
      transition: "cut",
      notes: "Trust builder moved earlier",
    },
    {
      id: "clip_product",
      name: "Product Demo",
      type: "video",
      start: 18,
      end: 28,
      order: 4,
      caption: "Deploy voice agents in minutes",
      transition: "slide",
      notes: "Product explanation, trimmed",
    },
    {
      id: "clip_cta",
      name: "CTA",
      type: "video",
      start: 28,
      end: 35,
      order: 5,
      caption: "Try it free today",
      transition: "fade_out",
      notes: "Earlier call to action",
    },
  ],
  audio: {
    musicMood: "energetic",
    volume: 80,
    voiceoverVolume: 90,
  },
  captions: {
    style: "bold_yellow",
    font: "Inter",
    size: "large",
    position: "bottom_center",
  },
};

const premiumInvestorCutTimeline: Timeline = {
  duration: 60,
  globalStyle: {
    pacing: "medium_fast",
    colorGrade: "premium_warm",
    musicMood: "cinematic",
    captionStyle: "clean_white",
    brandTone: "premium_confident",
  },
  clips: [
    {
      id: "clip_hook",
      name: "Hook",
      type: "video",
      start: 0,
      end: 5,
      order: 1,
      caption: "Built for the future of customer conversation",
      transition: "fade",
      notes: "Cinematic hook",
    },
    {
      id: "clip_problem",
      name: "Problem",
      type: "video",
      start: 5,
      end: 18,
      order: 2,
      caption: "Support teams are drowning in repetitive calls",
      transition: "cut",
      notes: "Pain point",
    },
    {
      id: "clip_product",
      name: "Product Demo",
      type: "video",
      start: 18,
      end: 36,
      order: 3,
      caption: "Deploy voice agents in minutes",
      transition: "slide",
      notes: "Product explanation",
    },
    {
      id: "clip_testimonial",
      name: "Customer Proof",
      type: "video",
      start: 36,
      end: 45,
      order: 4,
      caption: "Reduced support load by 40%",
      transition: "cut",
      notes: "Trust builder",
    },
    {
      id: "clip_cta",
      name: "CTA",
      type: "video",
      start: 45,
      end: 60,
      order: 5,
      caption: "Partner with us",
      transition: "fade_out",
      notes: "Investor-facing call to action",
    },
  ],
  audio: {
    musicMood: "cinematic",
    volume: 65,
    voiceoverVolume: 95,
  },
  captions: {
    style: "clean_white",
    font: "Inter",
    size: "medium",
    position: "bottom_center",
  },
};

const founderFeedbackCutTimeline: Timeline = {
  duration: 40,
  globalStyle: {
    pacing: "fast",
    colorGrade: "warm",
    musicMood: "confident",
    captionStyle: "bold_white",
    brandTone: "confident_direct",
  },
  clips: [
    {
      id: "clip_hook",
      name: "Hook",
      type: "video",
      start: 0,
      end: 4,
      order: 1,
      caption: "The teammate that never sleeps",
      transition: "cut",
      notes: "Founder-requested punchier hook",
    },
    {
      id: "clip_problem",
      name: "Problem",
      type: "video",
      start: 4,
      end: 14,
      order: 2,
      caption: "Support teams are drowning in repetitive calls",
      transition: "cut",
      notes: "Pain point",
    },
    {
      id: "clip_product",
      name: "Product Demo",
      type: "video",
      start: 14,
      end: 26,
      order: 3,
      caption: "Deploy voice agents in minutes",
      transition: "slide",
      notes: "Product explanation",
    },
    {
      id: "clip_testimonial",
      name: "Customer Proof",
      type: "video",
      start: 26,
      end: 32,
      order: 4,
      caption: "Reduced support load by 40%",
      transition: "cut",
      notes: "Trust builder",
    },
    {
      id: "clip_cta",
      name: "CTA",
      type: "video",
      start: 32,
      end: 40,
      order: 5,
      caption: "Book a demo today",
      transition: "fade_out",
      notes: "Founder wants earlier CTA",
    },
  ],
  audio: {
    musicMood: "confident",
    volume: 75,
    voiceoverVolume: 90,
  },
  captions: {
    style: "bold_white",
    font: "Inter",
    size: "large",
    position: "bottom_center",
  },
};

export const BRANCH_IDS = {
  main: "branch-main-cut",
  fastReel: "branch-fast-reel-cut",
  premiumInvestor: "branch-premium-investor-cut",
  founderFeedback: "branch-founder-feedback-cut",
} as const;

// The uploaded demo video was split into four pieces (public/demo/part-*.mp4).
// Each story clip maps to one piece, so every branch renders the real footage —
// the same source material, cut and styled differently per person's version.
const SOURCE_BY_CLIP: Record<string, string> = {
  clip_hook: "/demo/part-1.mp4",
  clip_problem: "/demo/part-2.mp4",
  clip_product: "/demo/part-3.mp4",
  clip_testimonial: "/demo/part-4.mp4",
  clip_cta: "/demo/part-1.mp4",
};

// Inject the shared source footage into a timeline's clips by role. Kept separate
// from the timeline literals so the branch-specific edits (pacing, captions,
// grade) stay readable above.
function withSources(timeline: Timeline): Timeline {
  return {
    ...timeline,
    clips: timeline.clips.map((clip) => ({
      ...clip,
      sourceUrl: clip.sourceUrl ?? SOURCE_BY_CLIP[clip.id],
    })),
  };
}

export const seedBranches: Branch[] = [
  {
    id: BRANCH_IDS.main,
    projectId: PROJECT_ID,
    name: "Main Cut",
    status: "approved",
    timeline: withSources(mainCutTimeline),
    createdBy: "Mani",
    createdAt: "2026-06-20T09:15:00.000Z",
    updatedAt: "2026-06-20T09:15:00.000Z",
  },
  {
    id: BRANCH_IDS.fastReel,
    projectId: PROJECT_ID,
    name: "Fast Reel Cut",
    parentBranchId: BRANCH_IDS.main,
    status: "draft",
    timeline: withSources(fastReelCutTimeline),
    createdBy: "Riya",
    createdAt: "2026-06-21T11:30:00.000Z",
    updatedAt: "2026-06-21T11:30:00.000Z",
  },
  {
    id: BRANCH_IDS.premiumInvestor,
    projectId: PROJECT_ID,
    name: "Premium Investor Cut",
    parentBranchId: BRANCH_IDS.main,
    status: "draft",
    timeline: withSources(premiumInvestorCutTimeline),
    createdBy: "Priya",
    createdAt: "2026-06-22T14:00:00.000Z",
    updatedAt: "2026-06-22T14:00:00.000Z",
  },
  {
    id: BRANCH_IDS.founderFeedback,
    projectId: PROJECT_ID,
    name: "Founder Feedback Cut",
    parentBranchId: BRANCH_IDS.main,
    status: "draft",
    timeline: withSources(founderFeedbackCutTimeline),
    createdBy: "Zane",
    createdAt: "2026-06-23T16:45:00.000Z",
    updatedAt: "2026-06-23T16:45:00.000Z",
  },
];

export const seedComments: Comment[] = [
  {
    id: "comment-1",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.main,
    clipId: "clip_hook",
    timestampSeconds: 2,
    author: "Zane",
    body: "This hook feels a little slow for the first 3 seconds. Can we get to the point faster?",
    createdAt: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "comment-2",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.main,
    clipId: "clip_cta",
    timestampSeconds: 52,
    author: "Priya",
    body: "Client wants the CTA to feel more premium, less generic 'book a demo'.",
    createdAt: "2026-06-20T10:20:00.000Z",
  },
  {
    id: "comment-3",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.main,
    clipId: "clip_problem",
    author: "Riya",
    body: "Captions here are hard to read over the dark background. Let's test bolder styles.",
    createdAt: "2026-06-20T13:45:00.000Z",
  },
  {
    id: "comment-4",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.fastReel,
    clipId: "clip_hook",
    timestampSeconds: 1,
    author: "Zane",
    body: "This is the energy we need for Instagram. Ship it.",
    createdAt: "2026-06-21T12:00:00.000Z",
  },
  {
    id: "comment-5",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.fastReel,
    clipId: "clip_testimonial",
    author: "Mani",
    body: "Moving proof before the demo works surprisingly well for retention.",
    createdAt: "2026-06-21T12:30:00.000Z",
  },
  {
    id: "comment-6",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.fastReel,
    clipId: "clip_cta",
    author: "Riya",
    body: "Energetic music might be too loud under the CTA voiceover, worth a pass.",
    createdAt: "2026-06-21T13:10:00.000Z",
  },
  {
    id: "comment-7",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.premiumInvestor,
    clipId: "clip_hook",
    author: "Priya",
    body: "Cinematic score sells the premium tone immediately. Keep this.",
    createdAt: "2026-06-22T15:00:00.000Z",
  },
  {
    id: "comment-8",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.premiumInvestor,
    clipId: "clip_product",
    author: "Mani",
    body: "Consider trimming the demo by a couple seconds, investors are impatient.",
    createdAt: "2026-06-22T15:40:00.000Z",
  },
  {
    id: "comment-9",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.premiumInvestor,
    clipId: "clip_cta",
    author: "Zane",
    body: "'Partner with us' lands much better than 'book a demo' for this audience.",
    createdAt: "2026-06-22T16:10:00.000Z",
  },
  {
    id: "comment-10",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.founderFeedback,
    clipId: "clip_hook",
    author: "Zane",
    body: "This is the punchier hook I was asking for. Much better.",
    createdAt: "2026-06-23T17:00:00.000Z",
  },
  {
    id: "comment-11",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.founderFeedback,
    clipId: "clip_cta",
    author: "Riya",
    body: "Earlier CTA at 32s tests well, but let's not lose the testimonial punch before it.",
    createdAt: "2026-06-23T17:20:00.000Z",
  },
  {
    id: "comment-12",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.founderFeedback,
    clipId: "clip_problem",
    author: "Mani",
    body: "Warm grade throughout feels consistent with the brand now.",
    createdAt: "2026-06-23T17:45:00.000Z",
  },
];

export const seedTeamMemory: TeamMemory = {
  pacing: "medium",
  hookLengthPreference: "under_8_seconds",
  captionStyle: "minimal_white",
  colorGrade: "neutral",
  musicMood: "calm",
  transitionStyle: "clean_fades",
  ctaPlacement: "before_final_15_percent",
  brandTone: "clear_b2b",
  avoid: ["cluttered_text"],
  confidence: 0.55,
  lastUpdatedFromBranchId: BRANCH_IDS.main,
  updatedAt: "2026-06-20T09:15:00.000Z",
};

export const seedActivity: ActivityEvent[] = [
  {
    id: "activity-1",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.main,
    actor: "Mani",
    eventType: "branch_approved",
    message: "Mani approved Main Cut as the baseline",
    createdAt: "2026-06-20T09:20:00.000Z",
  },
  {
    id: "activity-2",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.fastReel,
    actor: "Riya",
    eventType: "branch_created",
    message: "Riya created Fast Reel Cut",
    createdAt: "2026-06-21T11:30:00.000Z",
  },
  {
    id: "activity-3",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.fastReel,
    actor: "Zane",
    eventType: "comment_added",
    message: "Zane commented on Hook",
    createdAt: "2026-06-21T12:00:00.000Z",
  },
  {
    id: "activity-4",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.premiumInvestor,
    actor: "Priya",
    eventType: "branch_created",
    message: "Priya created Premium Investor Cut",
    createdAt: "2026-06-22T14:00:00.000Z",
  },
  {
    id: "activity-5",
    projectId: PROJECT_ID,
    branchId: BRANCH_IDS.founderFeedback,
    actor: "Zane",
    eventType: "branch_created",
    message: "Zane created Founder Feedback Cut",
    createdAt: "2026-06-23T16:45:00.000Z",
  },
];
